if(EXISTS "/home/jyh/bustub-private/build_rel/test/orset_test[1]_tests.cmake")
  include("/home/jyh/bustub-private/build_rel/test/orset_test[1]_tests.cmake")
else()
  add_test(orset_test_NOT_BUILT orset_test_NOT_BUILT)
endif()
