if(EXISTS "/home/jyh/bustub-private/build_rel/test/type_test[1]_tests.cmake")
  include("/home/jyh/bustub-private/build_rel/test/type_test[1]_tests.cmake")
else()
  add_test(type_test_NOT_BUILT type_test_NOT_BUILT)
endif()
